repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      # Formatter
      - id: ruff
        args:
          - format
          - demos
          - examples
          - tests
          - src/trtutils

      # Linter
      - id: ruff
        args:
          - check
          - --fix
          - --preview
          - demos
          - examples
          - tests
          - src/trtutils
